version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Passw0rd2024"
    volumes:
      - ./docker/mssql/data:/var/opt/mssql
    ports:
      - "1433:1433"

  airflow:
    image: apache/airflow:latest
    container_name: airflow
    restart: always
    environment:
      - _AIRFLOW_WWW_USER=admin
      - _AIRFLOW_WWW_PASSWORD=admin
      - _AIRFLOW_WWW_EMAIL=meyssam.molaei@gmail.com
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    volumes:
      - ./docker/airflow/dags:/opt/airflow/dags
      - ./docker/airflow/data:/opt/airflow/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mssql
    command: standalone
