name: Deploy Docker Compose on Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Copy files to server
      run: |
        rsync -avz --exclude '.git/' . ubuntu@81.231.74.206:/home/memo/CICD

    - name: Deploy containers
      run: |
        ssh ubuntu@81.231.74.206 'cd /home/memo/CICD && bash scripts/prepare_dirs.sh && docker compose up -d --build'
